#!/usr/bin/env node

import { readFile, writeFile } from "fs/promises";
import path from "path";
import type { TemplateJson } from "@deep-sql-research/shared";

const CLI_HELP = `
Usage: render-video <template-json-file> [options]

Arguments:
  template-json-file    Path to the template JSON file generated by the research agent

Options:
  -o, --output <path>   Output video file path (default: ./output/video.mp4)
  -p, --preview         Start preview server instead of rendering
  -h, --help           Show this help message

Examples:
  render-video template.json
  render-video template.json -o ./my-video.mp4
  render-video template.json --preview
`;

async function main() {
  const args = process.argv.slice(2);
  
  if (args.includes('--help') || args.includes('-h')) {
    console.log(CLI_HELP);
    process.exit(0);
  }

  if (args.length === 0) {
    console.error('❌ Error: Template JSON file is required');
    console.log(CLI_HELP);
    process.exit(1);
  }

  const templateFile = args[0];
  if (!templateFile) {
    console.error('❌ Error: Template JSON file is required');
    console.log(CLI_HELP);
    process.exit(1);
  }
  
  const outputIndex = args.findIndex(arg => arg === '--output' || arg === '-o');
  const outputFile = outputIndex !== -1 && args[outputIndex + 1] 
    ? args[outputIndex + 1] 
    : './output/video.mp4';
  
  const previewMode = args.includes('--preview') || args.includes('-p');

  try {
    // Read and parse the template JSON
    console.log(`📖 Reading template from: ${templateFile}`);
    const templateContent = await readFile(templateFile, 'utf-8');
    const template: TemplateJson = JSON.parse(templateContent);

    console.log(`🎬 Processing template: "${template.meta.title}"`);
    console.log(`📊 ${template.dataBindings.insights.length} insights`);
    console.log(`🎬 ${template.timeline.scenes.length} scenes`);
    console.log(`🎴 ${template.cards.length} cards`);

    // Update the VideoRoot.tsx with the new template
    const videoRootPath = path.join(process.cwd(), 'src', 'VideoRoot.tsx');
    const videoRootCode = generateVideoRootCode(template);
    await writeFile(videoRootPath, videoRootCode, 'utf-8');

    if (previewMode) {
      console.log('👀 Starting preview server...');
      console.log('Run: bun run dev');
    } else {
      console.log(`🎥 Rendering video to: ${outputFile}`);
      console.log('Run: bun run build');
    }

    console.log('✅ Template loaded successfully!');

  } catch (error) {
    console.error('❌ Error:', error);
    process.exit(1);
  }
}

function generateVideoRootCode(template: TemplateJson): string {
  return `
import { Composition } from "remotion";
import { DynamicWrappedVideo } from "./components/DynamicWrappedVideo";
import type { TemplateJson } from "@deep-sql-research/shared";

export const RemotionRoot: React.FC = () => {
  const template: TemplateJson = ${JSON.stringify(template, null, 2)};

  return (
    <>
      <Composition
        id="${template.compositionId}"
        component={DynamicWrappedVideo}
        durationInFrames={Math.floor(${template.timeline.totalDuration} * 30)}
        fps={30}
        width={1920}
        height={1080}
        props={{ template }}
      />
    </>
  );
};

export default RemotionRoot;
`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}